practice/cms/urls.py
from django.conf.urls import url
from cms import views

urlpatterns=[
    url(r'^user/$', views.user_list, name='user_list'),
    url(r'^user/add/$', views.user_edit, name='user_add'),
    url(r'^user/mod/(?P<user_id>\d+)/$', views.user_edit, name='user_mod'),
    url(r'^user/del/(?P<user_id>\d+)/$', views.user_del, name='user_del'),
]

practice/practice/cms/urls.py
from django.conf.urls import url
from cms import views

urlpatterns=[
    url(r'^user/$', views.user_list, name='user_list'),
    url(r'^user/add/$', views.user_edit, name='user_add'),
    url(r'^user/mod/(?P<user_id>\d+)/$', views.user_edit, name='user_mod'),
    url(r'^user/del/(?P<user_id>\d+)/$', views.user_del, name='user_del'),
]

practice/practice/practice/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cms/', include('cms.urls', namespace='cms')),
]

practice/practice/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cms/', include('cms.urls', namespace='cms')),
]

practice/cms/models.py
from django.db import models


class User(models.Model):
    """顧客"""
    name=models.CharField('氏名',max_length=255)
    post=models.CharField('郵便番号',max_length=255)
    address=models.CharField('住所',max_length=255)

    def __str__(self):
        return self.name

practice/practice/cms/models.py
from django.db import models


class User(models.Model):
    """顧客"""
    name=models.CharField('氏名',max_length=255)
    post=models.CharField('郵便番号',max_length=255)
    address=models.CharField('住所',max_length=255)

    def __str__(self):
        return self.name

practice/cms/forms.py
from django.forms import ModelForm
from cms.models import User


class UserForm(ModelForm):
    """顧客のフォーム"""
    class Meta:
        model = User
        fields=('name','post','address')

practice/practice/cms/forms.py
from django.forms import ModelForm
from cms.models import User


class UserForm(ModelForm):
    """顧客のフォーム"""
    class Meta:
        model = User
        fields=('name','post','address')

practice/cms/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse

from cms.models import User
from cms.forms import UserForm


def user_list(request):
    """顧客一覧"""
    # return HttpResponse('顧客の一覧')
    users=User.objects.all().order_by('id')
    return render(request,
                  'cms/user_list.html',
                  {'users':users})


def user_edit(request, user_id=None):
    """顧客の編集"""
    # return HttpResponse('顧客の編集')
    if user_id:
        user = get_object_or_404(User, pk=user_id)
    else:
        user=User()

    if request.method == 'POST':
        form=UserForm(request.POST, instance=user)
        if form.is_valid():
            user=form.save(commit=False)
            user.save()
            return redirect('cms:user_list')
    else:
        form=UserForm(instance=user)

    return render(request, 'cms/user_edit.html', dict(form=form, user_id=user_id))

def user_del(request, user_id):
    """顧客の削除"""
    # return HttpResponse('顧客の削除')
    user=get_object_or_404(User, pk=user_id)
    user.delete()
    return redirect('cms:user_list')

practice/practice/cms/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse

from cms.models import User
from cms.forms import UserForm


def user_list(request):
    """顧客一覧"""
    # return HttpResponse('顧客の一覧')
    users=User.objects.all().order_by('id')
    return render(request,
                  'cms/user_list.html',
                  {'users':users})


def user_edit(request, user_id=None):
    """顧客の編集"""
    # return HttpResponse('顧客の編集')
    if user_id:
        user = get_object_or_404(User, pk=user_id)
    else:
        user=User()

    if request.method == 'POST':
        form=UserForm(request.POST, instance=user)
        if form.is_valid():
            user=form.save(commit=False)
            user.save()
            return redirect('cms:user_list')
    else:
        form=UserForm(instance=user)

    return render(request, 'cms/user_edit.html', dict(form=form, user_id=user_id))

def user_del(request, user_id):
    """顧客の削除"""
    # return HttpResponse('顧客の削除')
    user=get_object_or_404(User, pk=user_id)
    user.delete()
    return redirect('cms:user_list')

practice/cms/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang={{ LANGUAGE_CODE|default:"en-us" }}>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Users{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
<script src="{% static 'js/jquery-3.1.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block extrahead %}{% endblock %}
</head>
<body>
    <div class="container">
        {% block content %}
        {{ content }}
        {% endblock %}
    </div>

</body>
</html>

practice/cms/templates/cms/user_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}顧客の編集{% endblock %}

{% block content %}
    <h3 class="page-header">顧客の編集</h3>
    {% if user_id %}
    <form action="{% url 'cms:user_mod' user_id=user_id %}" method="post" class="form-horizontal"role="form">
    {% else %}
    <form action="{% url 'cms:user_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
        {% csrf_token %}
        {{ form|bootstrap_horizontal }}
        <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">送信</button>
                </div>
        </div>
    </form>
    <a href="{% url 'cms:user_list' %}" class="btn btn-default btn-sm">戻る</a>
{% endblock %}

practice/cms/templates/cms/user_list.html
{% extends "base.html" %}

{% block title %}顧客の一覧{% endblock title %}

{% block extrahead %}
<style>
    table{
        margin-top: 8px;
    }
</style>
{% endblock %}

{% block content %}
    <h3 class="page-header">顧客の一覧</h3>
    <a href="{% url 'cms:user_add' %}" class="btn btn-default btn-sm">追加</a>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>顧客ID</th>
                <th>氏名</th>
                <th>〒</th>
                <th>住所</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td><a href="{% url 'cms:user_mod' user_id=user.id %}"class="btn btn-default btn-sm">{{ user.id }}</a></td>
                <td>{{ user.name }}</td>
                <td>{{ user.post }}</td>
                <td>{{ user.address }}</td>
                <td><a href="{% url 'cms:user_del' user_id=user.id%}"class="btn btn-default btn-sm">削除</a></td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

practice/practice/cms/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang={{ LANGUAGE_CODE|default:"en-us" }}>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Users{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
<script src="{% static 'js/jquery-3.1.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block extrahead %}{% endblock %}
</head>
<body>
    <div class="container">
        {% block content %}
        {{ content }}
        {% endblock %}
    </div>

</body>
</html>

practice/practice/cms/templates/cms/user_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}顧客の編集{% endblock %}

{% block content %}
    <h3 class="page-header">顧客の編集</h3>
    {% if user_id %}
    <form action="{% url 'cms:user_mod' user_id=user_id %}" method="post" class="form-horizontal"role="form">
    {% else %}
    <form action="{% url 'cms:user_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
        {% csrf_token %}
        {{ form|bootstrap_horizontal }}
        <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">送信</button>
                </div>
        </div>
    </form>
    <a href="{% url 'cms:user_list' %}" class="btn btn-default btn-sm">戻る</a>
{% endblock %}

practice/practice/cms/templates/cms/user_list.html
{% extends "base.html" %}

{% block title %}顧客の一覧{% endblock title %}

{% block extrahead %}
<style>
    table{
        margin-top: 8px;
    }
</style>
{% endblock %}

{% block content %}
    <h3 class="page-header">顧客の一覧</h3>
    <a href="{% url 'cms:user_add' %}" class="btn btn-default btn-sm">追加</a>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>顧客ID</th>
                <th>氏名</th>
                <th>〒</th>
                <th>住所</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td><a href="{% url 'cms:user_mod' user_id=user.id %}"class="btn btn-default btn-sm">{{ user.id }}</a></td>
                <td>{{ user.name }}</td>
                <td>{{ user.post }}</td>
                <td>{{ user.address }}</td>
                <td><a href="{% url 'cms:user_del' user_id=user.id%}"class="btn btn-default btn-sm">削除</a></td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}